services:
  elaina-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: elaina-md
    restart: unless-stopped
    stdin_open: true
    tty: true
    environment:
      - NODE_ENV=production
      - TZ=Asia/Jakarta
    volumes:
      - ./data:/home/container/data
      - ./session:/home/container/session
      - ./tmp:/home/container/tmp
    ports:
      - "3000:3000"
